### ISSUE TITLE
BUILD-Readme.txt update

### ISSUE THREAD

**Issue by antoniogioiacom** [dzimbeck/BitBay#1]
proposing this change to the instructions relative linux build:

== Build ==

Linux i386:

`git clone https://github.com/dzimbeck/BitBay.git`
`cd BitBay`
`chmod +x linuxBitBay.sh`
`./linuxBitBay.sh --build`

Linux x86_64:

`git clone https://github.com/dzimbeck/BitBay.git`
`cd BitBay`
`chmod +x linuxBitBay64.sh`
`./linuxBitBay64.sh --build`

Options:
--reset: update dependencies, clone BitBay repository
--force: if you are using Debian version > 7

Example with options:
`./linuxBitBay64.sh --reset --force --build`

After successful build, bitbayd can be found in BitBay/src/ 

--------------------------------------

Additional notes:

- the --reset option creates a folder 'src2' in $HOME, this is hardcoded in the script, can be fixed
- the line 16: "win32: Debian 8 (jessie) x86_64 (VM or chroot)" i believe is not correct

**Comment by dzimbeck** [comment]
Your notes have been added to the readme, thanks! Also some feedback on your other comments...

Line 16 is for cross compiling windows 32 from Linux. It is correct. This was generated in Debian 8 (jessie) as notated. In fact, this is a challenging build for most people which is why we have scripts.

src2 is because we also have scripts for other daemons, and don't want them to overwrite each other.

Closing this issue now. Thanks.
