### ISSUE TITLE
[Feature Request] Angular Electron Marketplace and Wallet

### ISSUE THREAD

**Issue by oleersoy** [dzimbeck/BitBay#13]
Any chance we will see an Electron based Wallet and Marketplace?  Seems like it would offer better possibilities for scaling and distributing the platform ui.

[Native Desktop Apps with Angular and Electron](https://www.youtube.com/watch?v=u_vMChpZMCk)

There's also ngx admin which give you a lot right out of the gate:
http://akveo.com/ngx-admin/#/pages/dashboard
https://github.com/akveo/ngx-admin

**Comment by dzimbeck** [comment]
This is very cool! Honestly I don't have the time to work on that for now. However we welcome any branch that wants to attempt this. We hope to convert the Halo Python code to JavaScript so it runs everywhere and move most of the security to the client side since double deposit works very well with client side implementations. We could use a few more contributors.
