### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by salamsoliman** [dzimbeck/BitBay#20]
I tried to execute the windows bitbay market client.When the market client synchronize data, always show No internet connection.So, I followed this tutorial to update the bitbay.conf file :
https://forum.bitbay.market/t/client-and-wallet-troubleshooting/37

no worked,How can I do now?

**Comment by dzimbeck** [comment]
This Github is for the Bitbay QT and network. The Halo source code is not hosted on a public github, it's hosted on the server linked at bitbay.market. "No internet connection" may have something to do with either a proxy setup you have or unstable internet connection. It should refresh on it's own. Otherwise you can come to Slack and I can troubleshoot it with you.

**Comment by salamsoliman** [comment]
Thanks,I registered from https://bitbay.market/slack.and not received email yet.

**Comment by salamsoliman** [comment]
And why not upload the bitbay market source code to github and let developers involve ?

**Comment by dzimbeck** [comment]
Yes I will put it on Github. For now it's hosted at www.davtonia.com/bithalo/haloobf.zip
To keep competitive advantage mostly and prevent cloning. However we could release the OBF package. Probably after the peg. When you register on Slack the email invite is sent manually. If you put your email here I will add you immediately or you can wait and they should add you within the day.

**Comment by salamsoliman** [comment]
Please add yummyblockstack@gmail.com to slack, thanks.
